n = str(input('Digite o seu nome completo')).strip()
nome = n.split()
print('Muito prazer em lhe conehcer')
print('Seu Prieiro Nome é {}.'.format(nome[0]))
print('Seu ultimo nome é {}.'.format(nome[len(nome)-1]))
print(nome)
